### ISSUE TITLE
pam-krb5 password change

### ISSUE THREAD

**Issue by oditynet** [rra/pam-krb5#12]
please,help me. i want change password in domain. but if i will change passwork,then new password i will write in a field,where i was entered old password. it is not true. if i will eneter new password,then i will want create new form,where i will enter new password and click to button "Change". can you will do it?

**Comment by rra** [comment]
I'm afraid this project isn't what you're looking for. This is a system integration component for Linux systems to support local Kerberos authentication, not a Kerberos implementation itself, and it's essentially unrelated to Active Directory (which I assume is what you mean by domain). The `kpasswd` program included in standard Kerberos deployments like MIT Kerberos or Heimdal can change Active Directory passwords and may be closer to what you're looking for.
